name: Build and deploy to remote server

on:
  push:
    branches: [ "main" ]
    
env:
  image_tag: ${{ secrets.DOCKERHUB_USERNAME }}/vpnbot:latest
  container_name: vpnbot

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push Docker image
        uses: docker/build-push-action@v3.2.0
        with:
          push: true
          tags: ${{ env.image_tag }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - 
        name: Update container version via SSH
        uses: appleboy/ssh-action@master
        with: 
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            docker pull ${{ env.image_tag }}
            docker stop ${{ env.container_name }} || true && docker rm ${{ env.container_name }} || true
            docker run -d --name ${{ env.container_name }} \
              --env ConnectionStrings__DbConnection="${{ secrets.DB }}" \
              --env TelegramSettings__Token="${{ secrets.TG_BOT_TOKEN }}" \
              --env TelegramSettings__ChannelId="${{ secrets.TG_CHANNEL_ID }}" \
              --env XUISettings__BaseUrl="${{ secrets.XUI_BASERUL }}" \
              --env XUISettings__Username="${{ secrets.XUI_USERNAME }}" \
              --env XUISettings__Password="${{ secrets.XUI_PASSWORD }}" \
              --env VpnSettings__InboundId="${{ secrets.XUI_INBOUND_ID }}" \
              --env VpnSettings__SubLinkTemplate="${{ secrets.XUI_SUBLINK_TEMPLATE }}" \
              --restart unless-stopped \
            -p ${{ secrets.APP_PORT }}:80 ${{ env.image_tag }} 
